---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dmru01
  name: deployment-manager
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "secrets", "configmaps"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "persistentvolumeclaims", "services", "endpoints", "replicationcontrollers", "daemonsets", "statefulsets", "events", "secrets", "configmaps", "deployments/scale"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward", "pods/attach"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch.volcano.sh"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubeflow.org"]
  resources: ["poddefaults"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-manager-binding
  namespace: dmru01
subjects:
- kind: User
  name: "system:serviceaccount:dmru01:default"
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: "dmru01-cluster-user"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "dmru01-cluster-user"
subjects:
- kind: User
  name: "system:serviceaccount:dmru01:default"
  apiGroup: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "dmru01-cluster-user"
